### ISSUE TITLE
question: why is the output different for same input images?

### ISSUE THREAD

**Issue by jpuck** [luanfujun/deep-photo-styletransfer#14]
first, amazing work!

secondly, just curious why the apple colors have changed even though the two inputs are [identical][1]?

[1]:https://github.com/luanfujun/deep-photo-styletransfer/blob/ebf55d12e77375d0260f885410e968b45ba4096c/examples/style/tar23.png

**Comment by luanfujun** [comment]
Because we used two different masks for them. Check out the segmentation masks in example folder.

**Comment by jpuck** [comment]
thanks!
