### ISSUE TITLE
Error compiling 'cuda_utils.cu'.

### ISSUE THREAD

**Issue by njordsir** [luanfujun/deep-photo-styletransfer#17]
The error obtained is as shown below.

`vishi@vishi-workstation:~/NSTYLE/deep-photo-styletransfer$ make
/usr/local/cuda-8.0/bin /nvcc -arch sm_35 -O3 -DNDEBUG --compiler-options '-fPIC' -o libcuda_utils.so --shared cuda_utils.cu -I/home/vishi/torch/install    /include/THC -I/home/vishi/torch/install    /include/TH -I/home/vishi/torch/install    /include -L/home/vishi/torch/install    /lib -Xlinker -rpath,/home/vishi/torch/install    /lib -lluaT -lTHC -lTH -lpng 
make: execvp: /usr/local/cuda-8.0/bin: Permission denied 
make: *** [libcuda_utils.so] Error 127`

I do have the required permissions for the location mentioned in the error. 

The first two lines of the makefile were changed, as needed.

`PREFIX=/home/vishi/torch/install
 NVCC_PREFIX=/usr/local/cuda-8.0/bin`

**Comment by Milaine** [comment]
the command was not executed as root and the directory is outside of the home folder (/usr/local/cuda-8.0/bin),my guess is to try again as root or with sudu
sudo make [...]

**Comment by njordsir** [comment]
`sudo make` gives the same error. 
I even tried compiling from locations that should be non-conflicting and compiled as root from CUDA_HOME itself. I still get the same error.

**Comment by vermontleo** [comment]
in ubuntu 16.04 LTS, I got something wrong like:

> cannot find -lTHC
or
cannot find THC.h no such file

after I
`luarocks install torch`
`luarocks install cutorch`
everything was fine
