### ISSUE TITLE
how about put some pictures with people‘s face？

### ISSUE THREAD

**Issue by caomu** [luanfujun/deep-photo-styletransfer#18]
if the input picture is a people's face without making up, and the style is a made up face.
what is the result?

**Comment by beshanoe** [comment]
![Image](https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/final_results/best11_t_1000.png)

**Comment by DenisSergeevitch** [comment]
@beshanoe what was the source and effect?

**Comment by caomu** [comment]
@beshanoe 
would you post the source and effect?

**Comment by beshanoe** [comment]
@DenisSergeevitch @caomu guys, I just watched some files here https://github.com/luanfujun/deep-photo-styletransfer/tree/master/examples/final_results 
Apparently, they didn't add it to the main page because it's poor result
