### ISSUE TITLE
make clean && make includes THC.h but it's not found

### ISSUE THREAD

**Issue by Milaine** [luanfujun/deep-photo-styletransfer#19]
the structure of torch seems to have changed, THC isn't found at install/include/THC, moved to extra/cutorch/lib/THC.

Including the now found THC.h file results in another issue I already reported here;
https://github.com/torch/cutorch/issues/737

**Comment by luanfujun** [comment]
Can you try ``require cutorch`` in torch? To ensure that ``cutorch`` is installed properly.

**Comment by Cliffus** [comment]
I've fixed this issue by executing the following commands in terminal:

- cd to you torch directory, and execute the update.sh script
- second, execute "luarocks install cutorch"

**Comment by Milaine** [comment]
Trying your method I have encountered this issue https://github.com/BVLC/caffe/issues/5123

**Comment by liangpengfei** [comment]
@Milaine I think you may have changed the makefile content .Look up your makefile again and you will find that the HTC folder which is not exist before we execute torch update.sh script now appear in `torch/install/include/THC` and the *THCGeneral.h* file is also found here.

**ATTENTION**:the real `THCGeneral.h` is located in `torch/install/include/THC` after we execute torch update.sh script ,not the file `THCGeneral.h.in` located in `torch/extra/cutorch/lib/THC

so what you need to do is to check your makefile again and point to correct HTC folder.

**Comment by Milaine** [comment]
@liangpengfei the issue is gcc, the update.sh file is in the torch folder and is not connected to the makefile in the dps directory.
I'd need help to solve the gcc issue since the person that found the issue first just installed a different version of the operating system

**Comment by GeorgySerga** [comment]
```
luarocks install torch
luarocks install cutorch
```
Did the trick for me. Takes a lot of time to install, and requires several gigs during the installation.
