### ISSUE TITLE
Octave requirements

### ISSUE THREAD

**Issue by themightyoarfish** [luanfujun/deep-photo-styletransfer#20]
It should be noted that Octave 4.0 is required, and the Image package must be installed (`pkg install <archive>` and `pkg load image` from the Octave prompt) to run the `gen_laplacian.m` script. Furthermore, the `getLaplacian1` function is not found, since the `addpath` commands seem to have erroneous trailing slashes.

When that is done, the program doesn't seem to terminate:
```
octave:1> pkg load image
octave:2> run('gen_laplacian.m')
Working on image index = 1
warning: your version of GraphicsMagick limits images to 8 bits per pixel
```
on abortion, some output is printed, proving that it does compute something (takes hours for 6 images), but the log messages aren't displayed when printed apparently.

Is it normal that this takes so long?

Tested on Ubuntu 14.04 on an AWS P2 instance.

**Comment by njordsir** [comment]
It does work and takes a while to complete. You can test for a single image as shown.

```
pkg load image

addpath matting/ 
addpath gaimc/

in_name = '../examples/input/in1.png';
input = im2double(imread(in_name));
input = reshape_img(input, 700);

[h w c] = size(input);
A = getLaplacian1(input, zeros(h, w), 1e-7, 1);
[Ai, ~, ~] = find(A);
[rp ci ai] = sparse_to_csr(A);
Ai = sort(Ai);
Aj = ci;
Aval = ai;
CSR = [Ai, Aj, Aval];
save('Input_Laplacian_3x3_1e-7_CSR_xx.mat', 'CSR');
```

**Comment by tarvos21** [comment]
@themightyoarfish, I encountered the same problem, it stop there and no longer output anything, I checked the GPU, there is no process running on the GPU. What may be the problem, how do you solve it at last?

**Comment by themightyoarfish** [comment]
Use martinbenson's fork, I haven't used this repo any further.

**Comment by tarvos21** [comment]
@themightyoarfish, thanks, I will try it.
