### ISSUE TITLE
make: *** [libcuda_utils.so] Error 1

### ISSUE THREAD

**Issue by jayfallon** [luanfujun/deep-photo-styletransfer#21]
Working in MacOS, I've been able to install:

- Torch
- Matlab and Octave
- CUDA
- cudnn

Download VGG-19, but then on `make clean && make` I get the following error which has been driving me insane:

`ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libcuda_utils.so] Error 1`

Anyone have this problem or know of a fix?

**Comment by luanfujun** [comment]
did you add -lluajit to your makefile as in issue #5

**Comment by jayfallon** [comment]
Thank you, just saw that commented out in the makefile.
