### ISSUE TITLE
Examples : Name is nonexistent or not a directory

### ISSUE THREAD

**Issue by jayfallon** [luanfujun/deep-photo-styletransfer#23]
On MacOS after make, I `run('gen_laplacian/gen_laplacian.m')` using MatLab or Octave in the root folder and get this message.

`Trial>> run('gen_laplacian/gen_laplacian.m')
Warning: Name is nonexistent or not a directory: matting\ 
> In path (line 109)
  In addpath (line 88)
  In gen_laplacian (line 1)
  In run (line 86) 
Warning: Name is nonexistent or not a directory: gaimc\ 
> In path (line 109)
  In addpath (line 88)
  In gen_laplacian (line 2)
  In run (line 86) 
Working on image index = 1

ans =

   437   700     3

Compute Laplacian
Undefined function or variable 'getLaplacian1'.

Error in gen_laplacian (line 20)
    A = getLaplacian1(input, zeros(h, w), 1e-7, 1);

Error in run (line 86)
evalin('caller', [script ';']);`

Not sure this path linking is supposed to work as all directories are present.

**Comment by themightyoarfish** [comment]
I had to remove the trailing backslashes from the `addpath` commands in `gen_laplacian.m`, maybe they work in Matlab (can't imagine why, except that maybe it swallows windows-style path separators without complaint), but not in Octave.

**Comment by luanfujun** [comment]
Ok, I have modified the backslashes. thanks for the pointer

**Comment by jayfallon** [comment]
Thanks for pointing that out. I was trying step by step and removing the slashes is something I'd done yesterday with an incomplete install.
