### ISSUE TITLE
Where to find λ – "photorealism regularization weight" from paper in code | segmentation colors

### ISSUE THREAD

**Issue by subzerofun** [luanfujun/deep-photo-styletransfer#28]
Hey there, i was wondering where i can find the λ parameter from the original paper in your code.

The paper states that a value of 10e4 gave the best results, but i woud like to try to experiment a little bit with lower values. I imagine that a lower value could preserve more style detail – for the cost of looking more like the CNNMRF method.

Am i simply overlooking the parameter because it's named differently or is it hidden in the more complex functions?

![default](https://cloud.githubusercontent.com/assets/17863119/24436147/27c38710-143a-11e7-940b-3caea4a6dbec.png)

I also tried playing around with`f_radius` – reducing the value preserved more detail – transferred more style detail to the final image. Could you explain what `f_edge` does?

Since you have a lot of landscape examples, but no animals, my test example was an attempt to transfer the style of a tiger to a housecat 😀. Maybe CNNMRF would be better suited for that – but i wanted to take advantage of the photorealistic effect of this method. CNNMRF would make the final image look more like a painting, and i've seen that often enough by now. 
The masking of your method offers a great degree of control for finetuning how you want your output to look like. 
EDIT: I wrote lion, but of course it's a tiger... Note to self: stripes? = tiger. no stripes, furry mane? = lion. If you f*ck with nature? = [liger](http://www.liger-hercules.com/liger-hercules-moksha-bybee/liger-hercules-moksha-bybee-liger-cub-aries.jpg)

![in62](https://cloud.githubusercontent.com/assets/17863119/24436716/6e47471e-143d-11e7-9d1d-525ad3b05def.png)

![tar62](https://cloud.githubusercontent.com/assets/17863119/24436714/68ed9d5e-143d-11e7-9e5d-e0b399f2e92e.png)

Temp result (neural style):

![out_62_550_t_1000](https://cloud.githubusercontent.com/assets/17863119/24436751/91866a48-143d-11e7-8b4b-6792ef7a23c2.png)

 **Final results :-) :** (f_radius @ 5 – 0.5)

![best62_t_1000](https://cloud.githubusercontent.com/assets/17863119/24436781/b80c43e0-143d-11e7-8426-0e6f606b1331.png)

![best62_t_1000](https://cloud.githubusercontent.com/assets/17863119/24436765/9d5a5a0a-143d-11e7-956e-6f8c131923ef.png)

![best62_t_1000](https://cloud.githubusercontent.com/assets/17863119/24436773/b15ff6d6-143d-11e7-8e0a-2afdf5d3d44c.png)

![out_62_550x380px_t_300_f3_e0 01](https://cloud.githubusercontent.com/assets/17863119/24436702/5e857008-143d-11e7-8e25-6d07069b11fe.png)

And the masks:
![in62](https://cloud.githubusercontent.com/assets/17863119/24436880/3dd807ca-143e-11e7-9643-7129396aa17b.png)
![tar62](https://cloud.githubusercontent.com/assets/17863119/24436882/3fbb8f9e-143e-11e7-9253-e568a1a48ce6.png)

---

### **Mask colors**

Another quick question about the colors you can use for your mask pngs: In `neuralstyle_seg.lua` and `deepmatting_seg.lua` you define that these colors are processed from the segmentation images:
```lua
`local color_codes = {'blue', 'green', 'black', 'white', 'red', 'yellow', 'grey', 'lightblue', 'purple'}`
```

The problem for me (and maybe others users too) was to recognize that you are restricted to these colors when you "paint" your masks. At first i didn't look at the code and just chose random colors – i only realized that something was wrong when the generated output didn't match my selections.

So could you maybe include a info in your Readme how to manually create a mask – which colors you can use (maybe hex colors?). I'm not sure if everyone automatically knows what colors are actually processed.

Thanks!

**Comment by martinbenson** [comment]
Line 33 in deepmatting_seg.lua:

cmd:option('-lambda', 1e4) 

You can change the default value there or add the -lambda flag in gen_all.py to set it.

**Comment by subzerofun** [comment]
Thanks – it's not even that hard to miss. Should've looked more carefully at the code.
