### ISSUE TITLE
Some scene parsing/segmentation tools

### ISSUE THREAD

**Issue by luanfujun** [luanfujun/deep-photo-styletransfer#3]
As people requested, here are some automatic or manual tools for creating a segmentation mask for a photo image:

Automatic:
1. MIT Scene Parsing: http://sceneparsing.csail.mit.edu/
2. SuperParsing: http://www.cs.unc.edu/~jtighe/Papers/ECCV10/
3. Nonparametric Scene Parsing: http://people.csail.mit.edu/celiu/LabelTransfer/
4. Berkeley: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html
5. CRF-RNN for Semantic Image Segmentation: https://github.com/torrvision/crfasrnn
6. Selective Search: https://github.com/belltailjp/selective_search_py

Manual:
1. Photoshop Quick Selection Tool: https://helpx.adobe.com/photoshop/using/making-quick-selections.html

**Comment by ghwatson** [comment]
For people who don't have access to photoshop, GIMP is also available: https://docs.gimp.org/en/gimp-tools-selection.html
