### ISSUE TITLE
Make a product based on this white paper?

### ISSUE THREAD

**Issue by nike-17** [luanfujun/deep-photo-styletransfer#30]
I and some my friends are excited to try to build real ios/android app based on this white paper ideas.
We do not have to limit our scope with it, but we feel impressed by this demo.
If you are interested in participating drop me an email to nikita@groshin.com - I add you to our trello/slack.

**Comment by MrZoidberg** [comment]
Have you already tried running torch on iOS or you're planning to use TensorFlow, or Accelerate?

**Comment by nike-17** [comment]
we are more sinking on client-server approach. But we are open to any ideas, drop me an email if you want to join.

**Comment by luanfujun** [comment]
hi @nike-17, I am not sure if you can develop product because Adobe put a license on it...

**Comment by nike-17** [comment]
we are based on the idea, not on implementation.

**Comment by nike-17** [comment]
We are not really sure how Adobe related to it?

**Comment by luanfujun** [comment]
@nike-17 , this work was done when I was an intern at Adobe. They might already fill a patent on this work.

**Comment by nike-17** [comment]
In this case, we will base our activity on ideas that are not mentioned in this whitepaper.
There is plenty fish in the see.

**Comment by luanfujun** [comment]
@nike-17 , ok, I will forward you to the lawyers by email.

**Comment by sparis** [comment]
Thanks for your interest, Nikita. I have asked for advice and below is the answer.
> Adobe declines to publicly comment on the specifics of our intellectual property, including our patent portfolio. You should discuss potential intellectual property issues with your own counsel prior to implementing ideas contained in any white papers.

**Comment by viatcheslavmogilevsky** [comment]
@nike-17 would you want to make online app?

**Comment by martinbenson** [comment]
My understanding is that you can't patent an abstract algorithm, only a specific implementation of one.

**Comment by subzerofun** [comment]
@luanfujun question not related to the issue: you worked as an intern at Adobe? Cool! Do you know of any plans that Adobe will add features like this to Photoshop in the future? If you are allowed to tell of course.

**Comment by luanfujun** [comment]
@subzerofun, I cannot comment on any of the Adobe plans.

**Comment by subzerofun** [comment]
@luanfujun OK, it would have surprised me if you would be allowed to talk about this. Nevertheless i still envy you for working at Adobe!
