### ISSUE TITLE
Add info to Readme about mask colors (RGB or hex values) that are recognized by neuralstyle_seg.lua & deepmatting_seg.lua

### ISSUE THREAD

**Issue by subzerofun** [luanfujun/deep-photo-styletransfer#37]
I've already mentioned this here: https://github.com/luanfujun/deep-photo-styletransfer/issues/28
But i thought it would be better to add a separate issue for it.

---

### **Mask colors**

A quick question about the colors you can use for your mask pngs: In `neuralstyle_seg.lua` and `deepmatting_seg.lua` you define that these colors are processed from the segmentation images:
```lua
`local color_codes = {'blue', 'green', 'black', 'white', 'red', 'yellow', 'grey', 'lightblue', 'purple'}`
```

The problem for me (and maybe others users too) was to recognize that you are restricted to these colors when you "paint" your masks. At first i didn't look at the code and just selected random colors in Photoshop – i only realized that something was wrong when the generated output didn't match my selections.

So could you maybe include a short info in your Readme about which colors you can use (maybe RGB + hex values?) when you manually create your masks?

I'm not sure if everyone automatically knows what colors are actually processed.

Thanks!

**Comment by themightyoarfish** [comment]
Were you successful in determining which colours to use precisely?

**Comment by themightyoarfish** [comment]
It appears the colour values can be read from 
```
if color == 'green' then 
    mask = torch.lt(seg[1], 0.1)
    mask:cmul(torch.gt(seg[2], 1-0.1))
    mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'black' then 
    mask = torch.lt(seg[1], 0.1)
    mask:cmul(torch.lt(seg[2], 0.1))
    mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'white' then
    mask = torch.gt(seg[1], 1-0.1)
    mask:cmul(torch.gt(seg[2], 1-0.1))
    mask:cmul(torch.gt(seg[3], 1-0.1))
  elseif color == 'red' then 
    mask = torch.gt(seg[1], 1-0.1)
    mask:cmul(torch.lt(seg[2], 0.1))
    mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'blue' then
    mask = torch.lt(seg[1], 0.1)
    mask:cmul(torch.lt(seg[2], 0.1))
    mask:cmul(torch.gt(seg[3], 1-0.1))
  elseif color == 'yellow' then
    mask = torch.gt(seg[1], 1-0.1)
    mask:cmul(torch.gt(seg[2], 1-0.1))
    mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'grey' then 
    mask = torch.cmul(torch.gt(seg[1], 0.5-0.1), torch.lt(seg[1], 0.5+0.1))
    mask:cmul(torch.cmul(torch.gt(seg[2], 0.5-0.1), torch.lt(seg[2], 0.5+0.1)))
    mask:cmul(torch.cmul(torch.gt(seg[3], 0.5-0.1), torch.lt(seg[3], 0.5+0.1)))
  elseif color == 'lightblue' then
    mask = torch.lt(seg[1], 0.1)
    mask:cmul(torch.gt(seg[2], 1-0.1))
    mask:cmul(torch.gt(seg[3], 1-0.1))
  elseif color == 'purple' then 
    mask = torch.gt(seg[1], 1-0.1)
    mask:cmul(torch.lt(seg[2], 0.1))
    mask:cmul(torch.gt(seg[3], 1-0.1))
```
The segmentation image's channels are probably in RGB order, so the rgb value by looking at the right case
```
    mask = torch.gt(seg[1], R)
    mask:cmul(torch.lt(seg[2], G))
    mask:cmul(torch.gt(seg[3], B))
```
Someone less lazy than myself should make a PR.

**Comment by subzerofun** [comment]
The colors follow a clear scheme, i've looked at the example mask pngs in Photoshop and picked the rgb values, they are defined like this:

| Color variable  | RGB Value | Hex Value |
| ------------- | ------------- | ------------- |
| `blue`  | `0 0 255`  | `0000ff`  |
| `green`  | `0 255 0`  | `00ff00`  |
| `black`  | `0 0 0`  | `000000`  |
| `white`  | `255 255 255`  | `ffffff`  |
| `red`  | `255 0 0`  | `ff0000`  |
| `yellow`  | `255 255 0`  | `ffff00`  |
| `grey`  | `128 128 128`  | `808080`  |
| `lightblue`  | `0 255 255`  | `00ffff`  |
| `purple`  | `255 0 255`  | `ff00ff ` |

Here is a test image using all available colors:
![mask_colors](https://cloud.githubusercontent.com/assets/17863119/24587249/4829ec2a-17b3-11e7-8187-bd6228a2ed27.png)

The intention of this issue thread is only an appeal to @luanfujun that he adds this info to the Readme – so that people who create their own masks in image editors know which colors they can use.

I guess you could alter the .lua files and add your own colors – but for most users these 9 should be enough.

**Comment by themightyoarfish** [comment]
Yeah from what I posted you can see the cutoff values, so you don't necessarily need pure colours.

**Comment by luanfujun** [comment]
@subzerofun , thanks for pointing this out! I will add it to Readme

**Comment by luanfujun** [comment]
I was lazy when writing this part of code. A more suitable way might be a map of integer <-> category...

**Comment by ProGamerGov** [comment]
@luanfujun Where would I find information on how to go about adding more colors?

**Comment by ProGamerGov** [comment]
> I was lazy when writing this part of code. A more suitable way might be a map of integer <-> category...

@luanfujun Could you please elaborate more on this comment? Would this allow for more colors to be used in masks? How would one go about replacing the current color mask system with what you describe?
