### ISSUE TITLE
Is removing the Matlab dependency possible?

### ISSUE THREAD

**Issue by ProGamerGov** [luanfujun/deep-photo-styletransfer#4]
I'd love to experiment with this project, but I'd rather not have to buy Matlab first as it is not free like Torch, Tensorflow, Theano, Caffe, etc...

 So is removing the Matlab dependency possible? And if so, how difficult would it be?

**Comment by luanfujun** [comment]
Ah... Yes it is possible. The only Matlab part in this project is to compute the matting Laplacian matrix, Eq. 12 in this [paper](http://www.wisdom.weizmann.ac.il/~levina/papers/Matting-Levin-Lischinski-Weiss-CVPR06.pdf) with their Matlab [code](http://www.wisdom.weizmann.ac.il/~levina/matting.tar.gz). Similar issue to #1.

**Comment by ProGamerGov** [comment]
@luanfujun Is using Octave: https://www.gnu.org/software/octave/ instead of Matlab possible without modifying the code? Octave appears to support all the required Matlab stuff, and it's free and open source software.

**Comment by luke14free** [comment]
first run 
`$ sudo apt-get install liboctave-dev`
then from octave after you downloaded image-2.6.1.tar.gz from https://octave.sourceforge.io/image/ run `pkg install image-2.6.1.tar.gz`, finally run `pkg load image`and then execute the script. Note that then I had an issue with some directories not being correctly imported (and there was an undefined getLaplacian1()), to fix it simply change the first two lines of the matlab file to:
```addpath matting/
addpath gaimc/``` (basically reversing the slash)

**Comment by martinbenson** [comment]
@luke14free I got Octave to work by doing the same things that you described, but the .Mat files it creates don't work in the deepmatting script for me. Do they work for you?

**Comment by mrubashkin-svds** [comment]
For Clarity on @luke14free comment:
On the command line:
```
cd [parent directory of deep-photo-styletransfer]
sudo apt-get install liboctave-dev
wget image-2.6.1.tar.gz from https://octave.sourceforge.io/image/
```
Then run *inside* of octave, by launching octave on the command line:
`octave`

```
pkg install image-2.6.1.tar.gz
pkg load image
run('deep-photo-styletransfer/gen_laplacian/gen_laplacian.m')
```

**Comment by NewETown** [comment]
Is there a solution for this running on Mac instead of Ubuntu? I'm running into the same `'im2double' undefined` problem trying to run `run('gen_laplacian/gen_laplacian.m')` :(

**Comment by martinbenson** [comment]
I removed the MATLAB/Octave dependency in my fork: https://github.com/martinbenson/deep-photo-styletransfer

**Comment by NewETown** [comment]
@martinbenson Thanks! This is perfect
