### ISSUE TITLE
How are you doing the segmentation?

### ISSUE THREAD

**Issue by nandexsp** [luanfujun/deep-photo-styletransfer#43]
Hi, 

how are you doing the segmentation? I tried to use selective search but the results are poors and doesnt work as I want. :(

Any Ideas?

**Comment by luanfujun** [comment]
For automatic segmentation you can something like this one: https://github.com/CSAILVision/sceneparsing 
or this one: http://www.cs.unc.edu/~jtighe/Papers/ECCV10/ 

For the masks we provided in this repository, they are generated using photoshop quick selection tool :-)
