### ISSUE TITLE
loading matting laplacian...	 err

### ISSUE THREAD

**Issue by LiuGangR** [luanfujun/deep-photo-styletransfer#50]
i use 1080ti and cuda8.0.And find this problem.

`loading matting laplacian...	gen_laplacian/Input_Laplacian_3x3_1e-7_CSR1.mat	
File could not be opened: gen_laplacian/Input_Laplacian_3x3_1e-7_CSR1.mat	
/home/pushi_dev/torch/install/bin/luajit: deepmatting_seg.lua:119: attempt to index a nil value
stack traceback:
	deepmatting_seg.lua:119: in function 'main'
	deepmatting_seg.lua:606: in main chunk
	[C]: in function 'dofile'
	..._dev/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
`

**Comment by luanfujun** [comment]
Did you check if the *.mat file is located in `gen_laplacian` directory?

**Comment by umudev** [comment]
*.mat files are located in that directory, still getting the same error.

**Comment by liebesu** [comment]
same issue
