### ISSUE TITLE
/example/high_res folder

### ISSUE THREAD

**Issue by John-HW-Cao** [luanfujun/deep-photo-styletransfer#52]
Hi

I have noticed that there is a huge difference in size and resolution between the content file and style file in the /example/high_res folder. And I have the question that

Is there any difference in the process of style-transferring between common figures in /example/input, /example/style folders and those high-resolution figures?

I am sorry, but I fail to see any comment on this topic in the paper. So could anyone please help me explain that?

**Comment by luanfujun** [comment]
Hi, we have some description about high_res in the supplementary: http://www.cs.cornell.edu/~fujun/files/style-cvpr17/style-cvpr17-supp.pdf
