### ISSUE TITLE
Manual segmentation

### ISSUE THREAD

**Issue by pennygalaxi** [luanfujun/deep-photo-styletransfer#7]
I would like to apply this algorithm to a new image with a new style (so the segmentations don't exist under examples/ folder). Therefore, I am trying to create segmentations that is required by the algorithm.

The Github page notes: "In the main paper we generate all comparison results using automatic scene segmenation algorithm modified from DilatedNet. Manual segmentation enables more diverse tasks hence we provide the masks in examples/segmentation/."

My questions are:
- which library did you exactly used for the segmentation? (I guess it is different from this one: https://github.com/fyu/dilation) since it says 'modified'?
- i am a bit confused by 'manual segmentation'? are the masks under examples/segmentation created manually? (if so, I appreciate if you can suggest some pointers on how to mark these segments manually, e.g. any interface that i can use) or were examples/segmentation masks created using dilanet?

Thanks,
Penny

**Comment by luanfujun** [comment]
#3
