### ISSUE TITLE
`in23.png` and `tar23.png` are identical

### ISSUE THREAD

**Issue by mathiasbynens** [luanfujun/deep-photo-styletransfer#8]
[`examples/input/in23.png`](https://github.com/luanfujun/deep-photo-styletransfer/blob/97c35ef3c7176d1020de358f50927d114f0c8e04/examples/input/in23.png) and [`examples/style/tar23.png`](https://github.com/luanfujun/deep-photo-styletransfer/blob/97c35ef3c7176d1020de358f50927d114f0c8e04/examples/style/tar23.png) are the same picture.

```
$ sha256sum in23.png tar23.png
1889c0094c038a11f7cee6afb3bda075b33bbcea090086539f3db81534f85fec  in23.png
1889c0094c038a11f7cee6afb3bda075b33bbcea090086539f3db81534f85fec  tar23.png
```

Is that intentional?

**Comment by luanfujun** [comment]
Yes, similar to issue #6.

**Comment by mathiasbynens** [comment]
Ah, my apologies for filing a duplicate issue!

So it’s okay that those files are okay because the masks in [`examples/segmentation/in23.png`](https://github.com/luanfujun/deep-photo-styletransfer/blob/97c35ef3c7176d1020de358f50927d114f0c8e04/examples/segmentation/in23.png) and [`examples/segmentation/tar23.png`](https://github.com/luanfujun/deep-photo-styletransfer/blob/97c35ef3c7176d1020de358f50927d114f0c8e04/examples/segmentation/tar23.png) are different.

Some suggestions that could help avoid this confusion:

1) include the masks in the Examples section in the README
2) Make [`examples/style/tar23.png`](https://github.com/luanfujun/deep-photo-styletransfer/blob/97c35ef3c7176d1020de358f50927d114f0c8e04/examples/style/tar23.png) a symlink to [`examples/input/in23.png`](https://github.com/luanfujun/deep-photo-styletransfer/blob/97c35ef3c7176d1020de358f50927d114f0c8e04/examples/input/in23.png) instead of duplicating the file in the repo. This not only saves disk space but it also makes it explicit/obvious to anyone browsing through the repo that these files are intended to be identical.

**Comment by maruscia** [comment]
I think that an explicit reference to [in23 segmentation mask](https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/segmentation/in23.png)  and [tar23 segmentation mask](https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/segmentation/tar23.png) images might be beneficial for the reader.

**Comment by luanfujun** [comment]
Have merged to repo.
